name: CI

on:
  push:
    branches: [ main, chore/infra-setup, feat/task-crud ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Node セットアップ (npm)
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # ルートの依存インストール
      - run: npm install

      # フロントエンドのビルド
      - run: |
          cd apps/web
          npm install
          npm run build

      # バックエンドのビルド（TypeScript コンパイル）
      - run: |
          cd apps/api
          npm install
          npm run build
